from __future__ import annotations

import unittest

from auto_ptu.rules.hooks import ability_hooks, move_specials


class HandlerCoverageTests(unittest.TestCase):
    def test_pending_ability_handlers_present(self) -> None:
        ability_hooks._load_ability_hooks()
        pending = [
            "Dragon's Maw",
            "Transistor",
        ]
        hooks = ability_hooks._ABILITY_HOOKS

        def has_ability(name: str) -> bool:
            key = name.lower()
            for entries in hooks.values():
                for ability, _holder, _func in entries:
                    if ability == key:
                        return True
            return False

        for name in pending:
            with self.subTest(ability=name):
                self.assertTrue(has_ability(name), f"Missing ability hook for {name}")

    def test_pending_move_handlers_present(self) -> None:
        move_specials.initialize_move_specials()
        pending = [
            "Mud Sport",
            "Name",
            "Nature's Madness",
            "Oblivion Wing",
            "Octazooka",
            "Ominous Wind",
            "Pain Split",
            "Parabolic Charge",
            "Parabolic Charge [SM]",
            "Parting Shot",
            "Pay Day",
            "Pierce!",
            "Play Nice",
            "Play Rough",
            "Pluck",
            "Poison Fang",
            "Poison Jab",
            "Poison Sting",
            "Powder",
            "Powder Snow",
            "Power Shift",
            "Power Split",
            "Power Swap",
            "Power Trick",
            "Power-Up Punch",
            "Psybeam",
            "Psychic Fangs",
            "Psychic Terrain",
            "Psyshield Bash",
            "Purify",
            "Quash",
            "Quick Guard",
            "Quiver Dance",
            "Rage",
            "Rage Powder",
            "Raging Fury",
            "Rain Dance",
            "Rapid Spin [SS]",
            "Razor Shell",
            "Recover",
            "Recycle",
            "Reflect",
            "Reflect Type",
            "Refresh",
            "Relic Song",
            "Rending Spell",
            "Resonance Beam",
            "Riposte",
            "Rising Voltage",
            "Roar",
            "Rock Climb",
            "Rock Polish",
            "Rock Slide",
            "Rock Smash",
            "Rock Throw",
            "Rock Tomb",
            "Rolling Kick",
            "Roost",
            "Rototiller",
            "Sacred Fire",
            "Safeguard",
            "Salvo",
            "Sand Attack",
            "Sand Tomb",
            "Sandstorm",
            "Scald",
            "Scary Face",
            "Scorching Sands",
            "Scratch",
            "Screech",
            "Searing Shot",
            "Secret Power",
            "Seed Bomb",
            "Seed Flare",
            "Shadow Ball",
            "Shadow Bone",
            "Shadow Sneak",
            "Sharpen",
            "Sheer Cold",
            "Shell Smash",
            "Shell Trap",
            "Shelter",
            "Shift Gear",
            "Shore Up",
            "Signal Beam",
            "Silver Wind",
            "Simple Beam",
            "Skill Swap",
            "Sky Uppercut",
            "Slack Off",
            "Sludge",
            "Sludge Bomb",
            "Sludge Wave",
            "Smack Down",
            "Smokescreen",
            "Snap Trap",
            "Snarl",
            "Snore",
            "Snatch",
            "Soak",
            "Soft-Boiled",
            "Spark",
            "Sparkling Aria",
            "Spectral Thief",
            "Speed Swap",
            "Spikes",
            "Spirit Break",
            "Spirit Lance",
            "Spirit Shackle",
            "Spite",
            "Splash",
            "Spore",
            "Spotlight",
            "Sprint",
            "Stealth Rock",
            "Steamroller",
            "Steel Wing",
            "Sticky Web",
            "Stomp",
            "Strength Sap",
            "String Shot",
            "Struggle Bug",
            "Struggle+",
            "Stuff Cheeks",
            "Substitute",
            "Sucker Punch",
            "Sucker Punch [SM]",
            "Sunny Day",
            "Sunsteel Strike",
            "Super Fang",
            "Superpower",
            "Supersonic",
            "Surf",
            "Swagger",
            "Swagger [SM]",
            "Swallow",
            "Sweet Kiss",
            "Sweet Scent",
            "Switcheroo",
            "Swords Dance",
            "Synchronoise",
            "Synthesis",
            "Tail Glow",
            "Tail Whip",
            "Tailwind",
            "Take Aim",
            "Take Heart",
            "Tar Shot",
            "Taunt",
            "Tearful Look",
            "Teatime",
            "Teeter Dance",
            "Telekinesis",
            "Teleport",
            "Terrorize",
            "Thief",
            "Thousand Arrows",
            "Thousand Waves",
            "Throat Chop",
            "Thunder Cage",
            "Thunder Fang",
            "Thunder Punch",
            "Thunder Shock",
            "Thunder Wave [SM]",
            "Thunderbolt",
            "Thunderous Kick",
            "Tickle",
            "Topsy-Turvy",
            "Torment",
            "Toxic Spikes",
            "Toxic Threads",
            "Trick",
            "Trick Room",
            "Trick-or-Treat",
            "Triple Arrows",
            "Triple Axel",
            "Triple Kick [LA]",
            "Trop Kick",
            "Twister",
            "U-Turn",
            "Uproar",
            "Vacuum Wave",
            "Vicegrip",
            "Victory Dance",
            "Vine Whip",
            "Volt Switch",
            "Water Pledge",
            "Water Pulse",
            "Water Sport",
            "Wear Down",
            "Whirlpool",
            "Wide Guard",
            "Will-O-Wisp",
            "Wing Attack",
            "Wish",
            "Wonder Room",
            "Work Up",
            "Worry Seed",
            "Wounding Strike",
            "Wrap",
            "X-Scissor",
            "Zen Headbutt",
            "Zing Zap",
        ]
        for name in pending:
            with self.subTest(move=name):
                self.assertTrue(
                    move_specials._has_specific_handler(name.lower()),
                    f"Missing move handler for {name}",
                )
